### ISSUE TITLE
用docker cli方式安装qbittorrent iyuu版本，那一堆命令行要输入到哪里去执行？

### ISSUE THREAD

**Issue by zwjie12** [devome/dockerfiles#1]
大佬，NAS上已经安装docker套件，那些部署qb的命令行是用SSH连接到NAS，切换到root账号，然后输入后运行吗？运行时提示-v，-e command not found

**Comment by devome** [comment]
那个多行命令是一起输入的，包括`\`在内。

**Comment by zwjie12** [comment]
> 那个多行命令是一起输入的，包括`\`在内。

大佬，两个问题再确认下，多谢。
  -e BT_PORT="34567"    `# BT监听端口，可自定义` \
1. 类似上面这行代码中两个单引号之间的中文不用删掉吧？
2. 那些多行命令是不是SSH连接到NAS，切换到root账号，输入后运行？

**Comment by devome** [comment]
> > 那个多行命令是一起输入的，包括`\`在内。
> 
> 大佬，两个问题再确认下，多谢。 -e BT_PORT="34567" `# BT监听端口，可自定义` \
> 
> 1. 类似上面这行代码中，#和后面的中文注释不用删掉吧？
> 2. 那些多行命令是不是SSH连接到NAS，切换到root账号，输入后运行？

1. 对，但要注意反引号```也不能删；
2. 对。

**Comment by zwjie12** [comment]
> > > 那个多行命令是一起输入的，包括`\`在内。
> > 
> > 
> > 大佬，两个问题再确认下，多谢。 -e BT_PORT="34567" `# BT监听端口，可自定义` \
> > 
> > 1. 类似上面这行代码中，#和后面的中文注释不用删掉吧？
> > 2. 那些多行命令是不是SSH连接到NAS，切换到root账号，输入后运行？
> 
> 1. 对，但要注意反引号`也不能删；
> 2. 对。

多谢大佬指点！
