### ISSUE TITLE
最新版本4.5.5种子自动分类执行报错

### ISSUE THREAD

**Issue by yellowstrong** [devome/dockerfiles#102]
<img width="866" alt="iShot_2023-09-06_23 41 09" src="https://github.com/devome/dockerfiles/assets/34505611/e250701c-4de4-43a0-8735-d45d6aedf722">

**Comment by yellowstrong** [comment]
测试回退使用4.5.4一切正常，今天更新最新版本后出现的问题

**Comment by devome** [comment]
nevinee/qbittorrent镜像重要更新说明

为保证用户安全，防止用户因使用反代并代理了127.0.0.1这种情况导致安全性降低，从2023年9月5日更新的镜像开始，创建容器需要新增设置两个环境变量：

QB_USERNAME（登陆qBittorrent的用户名）
QB_PASSWORD（登陆qBittorrent的密码）

容器将在创建时使用这两个环境变量去设置（如已存在配置文件则是修改）登陆qBittorent的用户名和密码。

如未设置这两个环境变量，或者保持为qBittorrent的默认值（默认用户名：admin，默认密码：adminadmin），则本容器附加的所有脚本、定时任务将无法继续使用。

详情：https://github.com/devome/dockerfiles/issues/101 

本消息只在设置了有效的通知渠道，并且未设置有效的 QB_USERNAME 和 QB_PASSWORD 这两个环境变量时，在创建容器时自动发送一次。

**Comment by yellowstrong** [comment]
> 为保证用户安全，防止用户因使用反代并代理了127.0.0.1这种情况导致安全性降低，从2023年9月5日更新的镜像开始，创建容器需要新增设置两个环境变量（不再自动设置对本地主机跳过身份验证）：
> 
> QB_USERNAME（登陆qBittorrent的用户名）
> QB_PASSWORD（登陆qBittorrent的密码）
> 
> 容器将在创建时使用这两个环境变量去设置（如已存在配置文件则是修改）登陆qBittorent的用户名和密码。
> 
> 如未设置这两个环境变量，或者保持为qBittorrent的默认值（QB_USERNAME：admin，QB_PASSWORD：adminadmin），则本容器附加的所有脚本、定时任务将无法继续使用（除非手动设置对本地主机跳过身份验证）。
> 
> 详情：https://github.com/devome/dockerfiles/issues/101 
> 
> 因上述原因，镜像默认安装好python，不再需要设置INSTALL_PYTHON这个环境变量。

是已经按照要求，设置了这两个环境变量，依旧报错

**Comment by devome** [comment]
把容器的控制台启动日志发下我看看

**Comment by yellowstrong** [comment]
> 把容器的控制台启动日志发下我看看

这个是我已经开启了打开对本地主机跳过验证，才分类成功，发送通知，关闭就会报错
![iShot_2023-09-07_09 32 14](https://github.com/devome/dockerfiles/assets/34505611/eb0c0dbd-53d3-45ea-be74-35bbf1e968e5)
密码是我自定义的，用户名试过其他的 也不行
![iShot_2023-09-07_09 33 15](https://github.com/devome/dockerfiles/assets/34505611/93cb82f4-13f0-48be-b8cb-9942021654f8)

**Comment by devome** [comment]
进入容器后执行下`bash -x /usr/local/bin/dl-finish <种子hash>`，你找一个在做种的hash，放在命令中，把全部输出发我看一下。

**Comment by yellowstrong** [comment]
> 先关闭对本地主机跳过身份验证，进入容器后执行下`bash -x /usr/local/bin/dl-finish <种子hash>`，你找一个在做种的hash，放在命令中，把全部输出发我看一下。

<img width="1195" alt="2023-09-07 10 54 21" src="https://github.com/devome/dockerfiles/assets/34505611/b56b4734-9240-47b2-be0e-32a9d4de371b">

**Comment by devome** [comment]
好像只是分类程序`auto-cat`有问题，我去看看是不是api接口改了。

**Comment by devome** [comment]
我更新了下脚本，现在你更新下镜像再看看出错不出错？

**Comment by yellowstrong** [comment]
正常了
