### ISSUE TITLE
宕机提醒太频繁了

### ISSUE THREAD

**Issue by spysir** [devome/dockerfiles#104]
镜像：nevinee/qbittorrent:edge
宕机提醒太频繁了，能否适当延长一点宕机检查间隔时间
![99999999999999999999](https://github.com/devome/dockerfiles/assets/59646715/44e94834-6909-49af-a1af-46670d1d9d46)

**Comment by devome** [comment]
1 健康检查可以自己设置检查的cron

2 如果没宕机但发送通知，那么应该是bug，你可以看看是不是#103 中我回复的情况。

**Comment by spysir** [comment]
> 1 健康检查可以自己设置检查的cron
> 
> 2 如果没宕机但发送通知，那么应该是bug，你可以看看是不是#103 中我回复的情况。

刚刚查看了一下，确实是没宕机却发送宕机通知，之前一直都没有出现这种情况

**Comment by devome** [comment]
看看是不是#103 帖子后面我回复另外一位网友的情况

**Comment by spysir** [comment]
> 看看是不是#103 帖子后面我回复另外一位网友的情况

我的情况不是连续发宕机通知，是每隔一段时间就会发宕机通知（实则没有宕机），之前用的这个nevinee/qbittorrent:edge镜像一直都没出现这种情况，跟103的帖子有点像

**Comment by devome** [comment]
我㧈edge镜像更新了，你更新下看看

**Comment by spysir** [comment]
> 我把edge镜像更新了，你更新下看看

感谢，已经更新，观察几个小时看看

**Comment by spysir** [comment]
能否添加关闭【宕机发通知】这一功能，因为【宕机发通知】没有那么必要，准确性也不高，其它的通知功能保留
下面图可以看到，4:12， 5:12，6:12每次健康检查一次就发送一次通知，实则是QB WEBUI是正常访问的
![111111111111111111111](https://github.com/devome/dockerfiles/assets/59646715/fdd27bb2-90d4-4ebf-ac03-9192ebfc5220)

**Comment by devome** [comment]
> 能否添加关闭【宕机发通知】这一功能，因为【宕机发通知】没有那么必要，准确性也不高，其它的通知功能保留
> 下面图可以看到，4:12， 5:12，6:12每次健康检查一次就发送一次通知，实则是QB WEBUI是正常访问的
> ![111111111111111111111](https://github.com/devome/dockerfiles/assets/59646715/fdd27bb2-90d4-4ebf-ac03-9192ebfc5220)
> 

我说过了，你可以自己用对应的环境变量自己设置，设置成一年一次就行。

**Comment by devome** [comment]
CRON_HEALTH_CHECK 这个

**Comment by devome** [comment]
> > CRON_HEALTH_CHECK 这个
> 
> 这样写对吗
> CRON_HEALTH_CHECK="* * * 12 *"

这是12月的每分钟，一年一次要指定月 日 时 分四项。
