### ISSUE TITLE
隔几天时间就会停止容器

### ISSUE THREAD

**Issue by cng10001** [devome/dockerfiles#106]
安装环境是群晖docker
隔几天或者一段时间容器就自动停掉了，感觉不正常，但也没什么警告，或者日志可以看~
会有这样的情况吗
![Snipaste_2023-09-26_18-01-25](https://github.com/devome/dockerfiles/assets/115156545/9115bb83-ba04-4bc4-ad9a-02a4bea019a0)

**Comment by devome** [comment]
qb自身不会自己退出，如果是主动退出，在容器的控制台日志（不是文件中的日志）中会有以下内容：

```
Catching signal: SIGTERM
Exiting cleanly
```

如果没有，就是其它原因。

**Comment by cng10001** [comment]
> qb自身不会自己退出，如果是主动退出，在容器的控制台日志（不是文件中的日志）中会有以下内容：
> 
> ```
> Catching signal: SIGTERM
> Exiting cleanly
> ```
> 
> 如果没有，就是其它原因。

额……docker里其他容器没有这样过啊 就摸不着头脑。还有个现象就是有时候会批量trackererror 点重新汇报感觉没什么反应，容器重新启动就好得很快~照这样看来是不是宽带网络的原因很可能- -

**Comment by cng10001** [comment]
![未工作](https://github.com/devome/dockerfiles/assets/115156545/5b15fef0-8a17-4a1b-8ba4-84af7c3a23f0)
如果相关网站tracker大批量trackererror 新添加的种子也不会下载一直显示等待中，但还是那样重启容器就立马恢复- -

**Comment by devome** [comment]
> ![未工作](https://github.com/devome/dockerfiles/assets/115156545/5b15fef0-8a17-4a1b-8ba4-84af7c3a23f0)
> 如果相关网站tracker大批量trackererror 新添加的种子也不会下载一直显示等待中，但还是那样重启容器就立马恢复- -

这个与本镜像无关哦，请向qb官方反馈。
