### ISSUE TITLE
请问如何做到下载完成自动根据种子保存路径添加tag

### ISSUE THREAD

**Issue by nukewarrior** [devome/dockerfiles#109]
比如，保存目的地是/downloads/movie，包含关键字「movie」就加上「movie」标签，同理打上「tv」，「anime」之类的标签。

谢谢🙏

**Comment by devome** [comment]
可以在容器内新建一个脚本`/data/diy/start.sh`如下：

```
#!/usr/bin/env bash

. /usr/local/bin/share
tag=$(echo $2 | awk -F/ '{print $2}')
$cmd_curl_post -d "hashes=$1&tags=${tag}" ${api_url_base}/torrents/addTags
```
给该脚本增加可执行权限后，在qb的`新增 torrent 时运行外部程序`填入`/data/diy/start.sh "%K" "%D"`

**Comment by nukewarrior** [comment]
> 可以在容器内新建一个脚本`/data/diy/start.sh`如下：
> 
> ```
> #!/usr/bin/env bash
> 
> . /usr/local/bin/share
> tag=$(echo $2 | awk -F/ '{print $2}')
> $cmd_curl_post -d "hashes=$1&tags=${tag}" ${api_url_base}/torrents/addTags
> ```
> 
> 给该脚本增加可执行权限后，在qb的`新增 torrent 时运行外部程序`填入`/data/diy/start.sh "%K" "%D"`

我不太懂shell脚本，请问`tag=$(echo $2 | awk -F/ '{print $2}')`是获取保存目录的最后一个层级的目录名称么？
比如:
`/downloads/HDH/movie` -> `movie`
`/downloads/MT/aa/anime` -> `anime`

谢谢🙏

**Comment by devome** [comment]
没有问题
