### ISSUE TITLE
控制台不再显示qbittorrent运行详细日志

### ISSUE THREAD

**Issue by nukewarrior** [devome/dockerfiles#113]
控制台：
<img width="912" alt="Xnip2023-10-25_01-31-18" src="https://github.com/devome/dockerfiles/assets/10683831/ae0bacda-fb48-4bfb-9ea4-eedb3dd4fe57">

日志文件：
<img width="1129" alt="image" src="https://github.com/devome/dockerfiles/assets/10683831/c8b48ab9-62b7-442d-aa16-55f9434cc19e">

rt，控制台不再输出详细运行日志了，`/data/logs`文件夹下还是有日志保存，请问这是有意设计如此不再让运行日志输出到控制台么？
如果需要继续输出的话，请问需要如何设置呢，谢谢🙏

**Comment by devome** [comment]
啊，使用了新的构建逻辑，暂时不支持输出支控制台了。

**Comment by nukewarrior** [comment]
> 啊，使用了新的构建逻辑，暂时不支持输出支控制台了。

哦，好吧，本来能输出到控制台的话，用dozzy查看还蛮方便的
