### ISSUE TITLE
4.6.0版本的qBittorrent在webui修改ip addr导致无法使用

### ISSUE THREAD

**Issue by smomop** [devome/dockerfiles#114]
4.5.5的版本没问题，升级到4.6.0就不行了，感觉是个bug
我没用使用默认的*，而是使用的hostname，昨天自动更新就挂了，希望作者在能打包个edge-{version}的镜像，以防不时之需

<img width="784" alt="Snipaste_2023-10-26_00-04-30" src="https://github.com/devome/dockerfiles/assets/63437136/9c7b0c65-6b00-4c85-a737-0caacae0911f">

**Comment by devome** [comment]
.看起来应该是不支持用hostname了，你可以在启动前把配置文件/data/config/qBittorrent.conf那行改掉。

**Comment by devome** [comment]
另外还有个可能，容器能支持的是容器的hostname，要在创建容器时设置的，宿主的hostname它是认不到的。

**Comment by smomop** [comment]
我倒是觉得hostname这个功能挺好的，不知道为啥不支持了，可惜可惜
