### ISSUE TITLE
当ENABLE_AUTO_CATEGORY= false时dl-finish "%I"还会自动分类当前种子。

### ISSUE THREAD

**Issue by fjjonline** [devome/dockerfiles#13]
当ENABLE_AUTO_CATEGORY= false时dl-finish "%I"还会自动分类当前种子。

auto-cat -i 应该也要检查ENABLE_AUTO_CATEGORY= false参数吧！

**Comment by devome** [comment]
实测`ENABLE_AUTO_CATEGORY=false`时不会自动分类。

**Comment by devome** [comment]
如果你指定运行 `auto-cat -i <hash>`，那当然会分类了，你都指定了分类还不让它分类？

**Comment by fjjonline** [comment]
可能我的版本还没更新问题，4.3.9。谢谢了

**Comment by devome** [comment]
> 

4.3.7+支持ENABLE_AUTO_CATEGORY
4.4.0+支持自动分类只分类那些没有分类的种子
