### ISSUE TITLE
建议添加【主机名称】备注

### ISSUE THREAD

**Issue by spysir** [devome/dockerfiles#134]
如果qBittorrent在多个服务器部署的话，添加一个【主机名称】进行备注将更容易进行快速区分

**Comment by spysir** [comment]
添加一个变量HOSTNAME
![9999999999999999999](https://github.com/user-attachments/assets/3dcd9d4d-0069-40d8-8f25-a2cb7053d2b7)

**Comment by devome** [comment]
指定容器的主机名是docker自身的功能，不需要我加环境变量。

**Comment by spysir** [comment]
添加的是宿主机的主机名称备注

**Comment by devome** [comment]
见 https://github.com/devome/dockerfiles/commit/16d03f4f013dd3011028b229a5fc7440f2cb599e
将在下次qBittorrent更新时合并进容器，你也也可以自己构建。
