### ISSUE TITLE
建议发布 libtorrentv1 镜像

### ISSUE THREAD

**Issue by yueban** [devome/dockerfiles#136]
libtorrent v2.0 存在严重的 io 性能问题，详见下面这篇文章。
https://www.baiblog.ren/posts/2023/qBittorrent_CIFS_IO_Performance_Issues

我自己升级 qbitorrent 4.6.x 半年来，也确实发现存在此问题。之前下载可以跑满带宽 100m/s，升级后基本保持在 20m/s。统计弹窗显示**写入缓存超负荷**会在几秒内上升至 30%，然后回归 0，循环往复。

感谢大佬的项目，已使用2年有余，很大地方便了种子管理。希望大佬闲暇之余可以考虑出一个 4.6.7 libtorrentv1 的镜像，万分感谢。

**Comment by devome** [comment]
可以自己编译，克隆本仓库，在qbittorrent目录下运行以下命令：
```shell
docker build -t qbittorrent --build-arg LIBTORRENT_VERSION=1 --build-arg QBITTORRENT_VERSION=4.6.7 .
```

**Comment by yueban** [comment]
好的，我试试。
