### ISSUE TITLE
BT_port环境变量不生效

### ISSUE THREAD

**Issue by mayziran** [devome/dockerfiles#137]
使用的是4.3.9版，设置后，传入端口依然随机

**Comment by devome** [comment]
你的配置问题，好好检查下。同时我不对旧版本的功能作任何保证，只对最新版本负责。

**Comment by mayziran** [comment]
> 你的配置问题，好好检查下。同时我不对旧版本的功能作任何保证，只对最新版本负责。

感谢回复，新建几次映像试了下，设置了环境变量和端口转发，新建的打开传入端口还是会生成新的，不过不影响使用设置下就行了。
