### ISSUE TITLE
qbittorrent 删除文件会进入同目录的.Trash-1000文件夹

### ISSUE THREAD

**Issue by Genicur** [devome/dockerfiles#138]
rt

**Comment by devome** [comment]
你自己设置的，qb 5.x的新功能。

**Comment by dizicheng** [comment]
相同问题，经过提示找到开关，关闭即可：
![image](https://github.com/user-attachments/assets/66e61a09-f994-4e30-9136-a7413c05b3dc)

**Comment by Genicur** [comment]
> 你自己设置的，qb 5.x的新功能。

似乎是默认设置，我没有动过设置。

**Comment by devome** [comment]
你自己改成不删除到回收站不就好了
