### ISSUE TITLE
“自动加tracker标签”功能很久以来都没有反应

### ISSUE THREAD

**Issue by LoneFireBlossom** [devome/dockerfiles#140]
qb 4.6.7，威联通nas
我有几个qb docker，CATEGORY_OR_TAG=tag，ENABLE_AUTO_CATEGORY=true，但是为什么新添加进来的种子一直都不添加tracker标签呢，不懂，都这么久了还是不加tag。
QB_PASSWORD和账户不是默认的。
这种问题应该怎么排查呢
![21018](https://github.com/user-attachments/assets/8530baf1-6146-4983-8683-9aa2ed36b9e7)

**Comment by devome** [comment]
最新版本有没有用？

**Comment by LoneFireBlossom** [comment]
> 最新版本有没有用？

😭因为葡萄一直不支持5.x所以没升级
今晚上回去试试

**Comment by LoneFireBlossom** [comment]
哦对了我补充一下，之前我是一直用4.3.9版本，刚开始用的时候很正常，都能自动加标签。但是后来就不行了。我设置啥的都被变过，不知道到底是什么出了问题。
之前其实我有升级到5.0.1版本用过几天，也是不能加标签（要不然图里这些都能加上标签了）。

**Comment by devome** [comment]
我实测下来没什么问题。。。你检查下你的定时任务对不对。

**Comment by LoneFireBlossom** [comment]
定时任务？
CRON_AUTO_CATEGORY
CRON_TRACKER_ERROR吗？
这两个我都没设置

**Comment by LoneFireBlossom** [comment]
并不是所有的容器都有这个问题。
比如威联通上这个容器似乎就是正常的，但明明他们都是用一样的配置。
![75177](https://github.com/user-attachments/assets/4ff9a6d5-0516-4abd-8b21-15e66533ddd3)

群晖DS920+上这个也有问题
![83629](https://github.com/user-attachments/assets/fce13d42-77da-441e-a3a7-d43c1e597df6)

**Comment by devome** [comment]
那你把创建命令或compose.yml发出来吧

**Comment by LoneFireBlossom** [comment]
我自己傻逼了。
ENABLE_AUTO_CATEGORY=ture……
