### ISSUE TITLE
PT站更改tracker，导致自动标签分类出现多个标签的情况是否可以改进

### ISSUE THREAD

**Issue by LoneFireBlossom** [devome/dockerfiles#141]
一个思路，仅仅是提出来，并不一定适合改。

问题：
现在有的PT站改tracker，例如从`www.abc.com`改成`www.xyz.com`。
在分类设置为按照标签分类的情况下，原来种子的标签是`abc`，现在又加了一个`xyz`。`abc`这个标签已经没用了，以后新加进来的种子都是`xyz`标签。
这造成了标签的冗余。
所以我考虑能否修改。

修改：
软件自动给家的PT站标签都加上`-PT`后缀，例如`abc-PT`，`xyz-PT`。
参考`trackererror`标签的运行。在脚本运行打标签时，把带`-PT`后缀的标签全部去除，然后重新运行一遍。这样就能解决。
（考虑加后缀是因为加在前面不太好看）

不一定都接受：
有的人可能不喜欢这么做。

**Comment by devome** [comment]
你说得对，有人不喜欢那也就不能推翻现在的逻辑了。
你可以自己在修改tracker以后把那些不用的标签手动删除掉。
