### ISSUE TITLE
4.4.1版本部署报错  exec: fatal: unable to exec bash: No such file or directory

### ISSUE THREAD

**Issue by Rocky-CN** [devome/dockerfiles#21]
作者你好。我用的是OMV系统，在安装4.4.1版本时就会一直报错。tags 选择`latest-iyuu`和`iyuu`都是相同的错误信息 
> **exec: fatal: unable to exec bash: No such file or directory**

最后将 tags 改为`4.4.0-iyuu`就能正常部署了。我个人猜想：是4.4.1版本的问题。

#### 容器日志：
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-addpackge: executing...
exec: fatal: unable to exec bash: No such file or directory
[cont-init.d] 10-addpackge: exited 127.
[cont-init.d] 20-mkdir: executing...
exec: fatal: unable to exec bash: No such file or directory
[cont-init.d] 20-mkdir: exited 127.
[cont-init.d] 30-config: executing...
exec: fatal: unable to exec bash: No such file or directory
[cont-init.d] 30-config: exited 127.
[cont-init.d] 40-fixuser: executing...
exec: fatal: unable to exec bash: No such file or directory
[cont-init.d] 40-fixuser: exited 127.
[cont-init.d] 50-crontab: executing...
exec: fatal: unable to exec bash: No such file or directory
[cont-init.d] 50-crontab: exited 127.
[cont-init.d] 60-iyuu: executing...
[cont-init.d] 60-iyuu: Clone IYUUAutoReseed script...
[cont-init.d] 60-iyuu: Cloning into '/tmp/iyuu'...
[cont-init.d] 60-iyuu: Current crontab is:
[cont-init.d] 60-iyuu: # do daily/weekly/monthly maintenance
[cont-init.d] 60-iyuu: # min	hour	day	month	weekday	command
[cont-init.d] 60-iyuu: */15	*	*	*	*	run-parts /etc/periodic/15min
[cont-init.d] 60-iyuu: 0	*	*	*	*	run-parts /etc/periodic/hourly
[cont-init.d] 60-iyuu: 0	2	*	*	*	run-parts /etc/periodic/daily
[cont-init.d] 60-iyuu: 0	3	*	*	6	run-parts /etc/periodic/weekly
[cont-init.d] 60-iyuu: 0	5	1	*	*	run-parts /etc/periodic/monthly
[cont-init.d] 60-iyuu:
[cont-init.d] 60-iyuu: # 更新并重启IYUU
[cont-init.d] 60-iyuu: 38 3-23/7 * * * cd /iyuu && git fetch --all && git reset --hard origin/master && git pull && php start.php restart -d
[cont-init.d] 60-iyuu: grep: /data/config/qBittorrent.conf: No such file or directory
[cont-init.d] 60-iyuu: /usr/local/bin/share: line 2: $'\r': command not found
[cont-init.d] 60-iyuu: /usr/local/bin/share: line 13: syntax error: unexpected end of file
[cont-init.d] 60-iyuu: IIIIIIIIIIYYYYYYY       YYYYYYYUUUUUUUU     UUUUUUUUUUUUUUUU     UUUUUUUU
[cont-init.d] 60-iyuu: I::::::::IY:::::Y       Y:::::YU::::::U     U::::::UU::::::U     U::::::U
[cont-init.d] 60-iyuu: I::::::::IY:::::Y       Y:::::YU::::::U     U::::::UU::::::U     U::::::U
[cont-init.d] 60-iyuu: II::::::IIY::::::Y     Y::::::YUU:::::U     U:::::UUUU:::::U     U:::::UU
[cont-init.d] 60-iyuu:   I::::I  YYY:::::Y   Y:::::YYY U:::::U     U:::::U  U:::::U     U:::::U
[cont-init.d] 60-iyuu:   I::::I     Y:::::Y Y:::::Y    U:::::D     D:::::U  U:::::D     D:::::U
[cont-init.d] 60-iyuu:   I::::I      Y:::::Y:::::Y     U:::::D     D:::::U  U:::::D     D:::::U
[cont-init.d] 60-iyuu:   I::::I       Y:::::::::Y      U:::::D     D:::::U  U:::::D     D:::::U
[cont-init.d] 60-iyuu:   I::::I        Y:::::::Y       U:::::D     D:::::U  U:::::D     D:::::U
[cont-init.d] 60-iyuu:   I::::I         Y:::::Y        U:::::D     D:::::U  U:::::D     D:::::U
[cont-init.d] 60-iyuu:   I::::I         Y:::::Y        U:::::D     D:::::U  U:::::D     D:::::U
[cont-init.d] 60-iyuu:   I::::I         Y:::::Y        U::::::U   U::::::U  U::::::U   U::::::U
[cont-init.d] 60-iyuu: II::::::II       Y:::::Y        U:::::::UUU:::::::U  U:::::::UUU:::::::U
[cont-init.d] 60-iyuu: I::::::::I    YYYY:::::YYYY      UU:::::::::::::UU    UU:::::::::::::UU
[cont-init.d] 60-iyuu: I::::::::I    Y:::::::::::Y        UU:::::::::UU        UU:::::::::UU
[cont-init.d] 60-iyuu: IIIIIIIIII    YYYYYYYYYYYYY          UUUUUUUUU            UUUUUUUUU
[cont-init.d] 60-iyuu: 1647928820.5421 当前时间：2022-03-22 14:00:20
[cont-init.d] 60-iyuu: 1647928820.5438 当前操作系统：Linux
[cont-init.d] 60-iyuu: 1647928820.5438 当前运行环境：Linux
[cont-init.d] 60-iyuu: 1647928820.5438 当前接口类型：cli
[cont-init.d] 60-iyuu: 1647928820.5438 PHP二进制文件：/usr/bin/php7
[cont-init.d] 60-iyuu: 1647928820.5438 PHP版本号：7.4.26
[cont-init.d] 60-iyuu: 1647928820.5438 正在加载composer包管理器...
[cont-init.d] 60-iyuu: 1647928820.5521 composer依赖载入完成！
[cont-init.d] 60-iyuu: 1647928820.5522 环境变量初始化完成！
[cont-init.d] 60-iyuu:
[cont-init.d] 60-iyuu: 1647928820.5529  检查配置，是否同时监听IPv6...
[cont-init.d] 60-iyuu: 1647928820.553  未检测到常规配置JSON文件。
[cont-init.d] 60-iyuu: Workerman[start.php] start in DAEMON mode
[cont-init.d] 60-iyuu: ------------------------------------------ WORKERMAN -------------------------------------------
[cont-init.d] 60-iyuu: Workerman version:4.0.17          PHP version:7.4.26
[cont-init.d] 60-iyuu: ------------------------------------------- WORKERS --------------------------------------------
[cont-init.d] 60-iyuu: proto   user            worker             listen                 processes    status
[cont-init.d] 60-iyuu: tcp     root            IYUUAutoReseed     http://0.0.0.0:8787    1             [OK]
[cont-init.d] 60-iyuu: tcp     root            IYUUFileMonitor    none                   1             [OK]
[cont-init.d] 60-iyuu: tcp     root            IYUUTask           none                   1             [OK]
[cont-init.d] 60-iyuu: ------------------------------------------------------------------------------------------------
[cont-init.d] 60-iyuu: Input "php start.php stop" to stop. Start success.
[cont-init.d] 60-iyuu:
[cont-init.d] 60-iyuu: exited 0.
[cont-init.d] done.
[services.d] starting services
exec: fatal: unable to exec bash: No such file or directory
exec: fatal: unable to exec bash: No such file or directory
exec: fatal: unable to exec bash: No such file or directory
exec: fatal: unable to exec bash: No such file or directory
exec: fatal: unable to exec bash: No such file or directory
exec: fatal: unable to exec bash: No such file or directory
[services.d] done.
exec: fatal: unable to exec bash: No such file or directory
exec: fatal: unable to exec bash: No such file or directory

**Comment by devome** [comment]
奇怪，我自己也在用4.4.1，用着好好的啊。 #20 这个issue也是同样的问题。

你是什么平台？amd64还是arm64还是armv7？

**Comment by Rocky-CN** [comment]
设备是我家云，arm64的。
```shell
root@Chainedbox:~# dpkg --print-architecture
arm64
```

**Comment by devome** [comment]
我晚上排查下arm64的问题

**Comment by devome** [comment]
> 设备是我家云，arm64的。
> 
> ```shell
> root@Chainedbox:~# dpkg --print-architecture
> arm64
> ```

我把arm64平台的重新更新了下，你删掉旧的镜像重新pull试试。

**Comment by Rocky-CN** [comment]
测试了`latest-iyuu`，可以正常部署了。
