### ISSUE TITLE
如何取消自启动

### ISSUE THREAD

**Issue by Feb17** [devome/dockerfiles#22]
你好作者。
我的host使用的是unraid，每次unraid重启，容器很快自启动了，但是我挂载的下载目录因为在另外一台VM (truenas)，VM启动比容器慢，导致qb识别不到下载目录。种子就直接报错了。

不知道是否有方案关闭自启动？ 
<img width="1452" alt="Snipaste_2022-03-28_14-38-31" src="https://user-images.githubusercontent.com/7236132/160340359-a459881c-9f50-4736-a404-da8ee4749758.png">

**Comment by devome** [comment]
两种方法：
1. 创建容器的设置 `--restart never`，然后每次需要手动启动。
2. 使用docker volume功能，让docker来自动挂载外部存储，让qb使用这个volume。我没有用过，我只是知道这个东西的存在，具体如何使用你要学习一下文档：https://docs.docker.com/storage/volumes/

**Comment by Feb17** [comment]
> 两种方法：
> 
> 1. 创建容器的设置 `--restart never`，然后每次需要手动启动。
> 2. 使用docker volume功能，让docker来自动挂载外部存储（自动检测直到挂载成功），然后让qb使用这个volume。我没有用过，我只是知道这个东西的存在，具体如何使用你要学习一下文档：https://docs.docker.com/storage/volumes/

'nevinee/qbittorrent:iyuu'
Error response from daemon: invalid restart policy 'never'

提示无效参数

**Comment by devome** [comment]
> > 两种方法：
> > 
> > 1. 创建容器的设置 `--restart never`，然后每次需要手动启动。
> > 2. 使用docker volume功能，让docker来自动挂载外部存储（自动检测直到挂载成功），然后让qb使用这个volume。我没有用过，我只是知道这个东西的存在，具体如何使用你要学习一下文档：https://docs.docker.com/storage/volumes/
> 
> 'nevinee/qbittorrent:iyuu' Error response from daemon: invalid restart policy 'never'
> 
> 提示无效参数

改成`--restart no`试试

**Comment by Feb17** [comment]
成功，谢谢作者
