### ISSUE TITLE
使用watchtower 4.3.8升级4.4.2后，种子详情栏不显示信息的问题

### ISSUE THREAD

**Issue by leverule** [devome/dockerfiles#23]
![image](https://user-images.githubusercontent.com/57491211/160360941-99d4fc73-256b-45ff-a2fa-9931cfd3a8ae.png)
底栏所有标签页面都没信息，包括tracker、用户、内容，重启容器也不行，但是种子正常保种上传中，请问怎么解决呢

**Comment by devome** [comment]
清空浏览器缓存后重启浏览器。

**Comment by leverule** [comment]
> 清空浏览器缓存后重启浏览器。

感谢大佬回复！！清空缓存后解决了，又学到一招
