### ISSUE TITLE
unraid中docker安装的问题

### ISSUE THREAD

**Issue by Hbxycch** [devome/dockerfiles#24]
unraid种docker安装的问题，在unraid中的docker安装，有办法指定安装的版本吗，每次安装都是4.4.2，有的站点不支持

**Comment by devome** [comment]
指定标签即可。

**Comment by Hbxycch** [comment]
我指定标签的话，值写`4.4.0-iyuu`，请问键参数应该写什么

**Comment by devome** [comment]
> 我指定标签的话，值写`4.4.0-iyuu`，请问键参数应该写什么

比如命令行创建时，指定镜像为 `nevinee/qbittorrent:4.4.0-iyuu`，至于unraid具体在哪里指定，我没有用过，不是很清楚。

**Comment by Hbxycch** [comment]
已解决，感谢支持
解决办法
原来存储库写的是‘nevinee/qbittorrent:iyuu’
只需把存储库增加版本号即可`nevinee/qbittorrent:4.4.0-iyuu`

**Comment by devome** [comment]
这翻译不行啊，竟然叫存储库，明明叫镜像....

**Comment by Hbxycch** [comment]
哈哈，unraid一直这么叫的，估计老外直接用的google翻译
