### ISSUE TITLE
TrackerError标签不自动移除的BUG

### ISSUE THREAD

**Issue by leverule** [devome/dockerfiles#27]
![image](https://user-images.githubusercontent.com/57491211/161373225-8ddf2a53-0831-4384-9538-c81f0b5774c9.png)
有手动添加标签的情况下，如果自动加了TrackerError标签，Tracker恢复后无法自动去掉TrackerError标签，未手动添加标签的种子无此问题
这个问题在4.3.8就有啦，最新版还有

**Comment by devome** [comment]
每次运行tracker-error命令会重新检查并重设标签，运行时间由你定义的CRON_TRACKER_ERROR确定。

**Comment by leverule** [comment]
可是图中的几个种子的Tracker已经恢复很久了，没异常。但是程序没有去除TrackerError标签

**Comment by leverule** [comment]
![image](https://user-images.githubusercontent.com/57491211/161374215-4785638b-24d9-4af9-b0d2-b8f0b412fe18.png)
没找到具体日志

**Comment by devome** [comment]
不好意思，确实有问题。已经制作的镜像不会再更新，本次修复将会整合进4.4.3版本，如想在你使用的版本中生效，请参考这个 [commit](https://github.com/devome/dockerfiles/commit/6e24bbc76d8cbf55db2ad326704234e5f747c4c0) 修改容器内的`/usr/local/bin/tracker-error`这两行。

**Comment by leverule** [comment]
> 不好意思，确实有问题。已经制作的镜像不会再更新，本次修复将会整合进4.4.3版本，如想在你使用的版本中生效，请参考这个 [commit](https://github.com/devome/dockerfiles/commit/a21bf2d92dec083ad19ecbd815bf2bd76675a228) 修改容器内的`/usr/local/bin/tracker-error`这两行。

好滴，作者大大辛苦了~
