### ISSUE TITLE
我在自己构建python镜像的时候出现错误

### ISSUE THREAD

**Issue by lion-goose** [devome/dockerfiles#28]
我想去掉python镜像设置的国内源，并且增加一些组件，所以根据dockerfile自己构建了一下镜像。
但是启动镜像出现了错误：
[+] Running 1/2
 ⠿ Network python_default  Created                                                                                      0.1s
 ⠿ Container python        Starting                                                                                     0.5s
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/init": stat /init: no such file or directory: unknown

不知道是哪一步出现了错误

**Comment by devome** [comment]
最新的镜像python:alpine仓库中已经没有s6-overlay这个包了，不能用这个dockerfile。

**Comment by lion-goose** [comment]
> 最新的镜像python:alpine仓库中已经没有s6-overlay这个包了，不能用这个dockerfile。

啊 原来是这样 谢谢大佬

**Comment by devome** [comment]
我更新了Dockerfile，现在可以用了，我也重新制作了镜像，已经推送到docker hub了，同时也已经把从镜像下载pip包的语句去掉了。

**Comment by lion-goose** [comment]
> 我更新了Dockerfile，现在可以用了，我也重新制作了镜像，已经推送到docker hub了，同时也已经把从镜像下载pip包的语句去掉了。

多谢大佬👏👏
