### ISSUE TITLE
请问大神有支持快速校验功能的计划吗

### ISSUE THREAD

**Issue by leverule** [devome/dockerfiles#33]
如这个项目：https://github.com/ChisBread/qbittorrent_skip_patch
IYUU辅种多个站点时，快速校验的准确度已经可以满足PT需求，方便快捷，期望加入此功能~~然后靠环境变量开启，谢过大神

**Comment by devome** [comment]
暂不考虑，不想本镜像受到快检的潜在安全性风险影响。

**Comment by leverule** [comment]
嗯嗯，感谢大神回复~
