### ISSUE TITLE
挂载不同磁盘

### ISSUE THREAD

**Issue by Wangs121** [devome/dockerfiles#35]
我的/data是挂载在`/volume1/dacker/qb`，然后我想下载目录放在`/volume2/video`
安装时候用的`-v /volume2/video:/video`
然后再软件里修改下载完毕文件的路径到`/video`会显示**`无法保存路径`**，直接用这个路径下载文件则下载错误

使用的是`nevinee/qbittorrent:4.4.2-iyuu`

**Comment by devome** [comment]
群晖不能用根路径来映射，对，/volume2/video就是这块磁盘的根路径。

**Comment by Wangs121** [comment]
我刚刚用`/volume2/video/film/`试了也不行

**Comment by devome** [comment]
前者能工作，后者不能工作，你找找二者之间的区别是什么？再针对性的解决。

**Comment by Wangs121** [comment]
找到解决办法了，是权限问题：[PGID改成101就可以了](https://zhuanlan.zhihu.com/p/395215763)，谢谢你
