### ISSUE TITLE
大佬可以添加开源的Gotify推送服务吗

### ISSUE THREAD

**Issue by spysir** [devome/dockerfiles#42]
现有的推送服务都是依赖第三方服务的，都要经过第三方服务器，不仅隐私没有保障，而且有些推送服务还有信息数量限制，甚至还存在封号的风险，所以，大佬可否考虑添加支持像Gotify这样的免费开源自托管的推送服务呢？Gotify不仅支持手机APP,而且还支持WEB端接收通知和管理通知

**Comment by devome** [comment]
见https://github.com/devome/dockerfiles/commit/592018d5b7378bc8383dd642d0a80714b60af2af 部署时使用edge标签测试，正式版要等到qb的4.4.4发布时合并。注意该标签当前没有arm64平台的，这个平台当前edge仓库的包有问题。
创建时增加GOTIFY_URL和GOTIFY_APP_TOKEN两个环境变量。如：
```
GOTIFY_URL=https://example.com:8080
GOTIFY_APP_TOKEN=BRnbDJdtpf1Uh9
```

**Comment by spysir** [comment]
> 见[592018d](https://github.com/devome/dockerfiles/commit/592018d5b7378bc8383dd642d0a80714b60af2af) ，部署时使用`nevinee/qbittorrent:edge`标签，正式版要等到qb的4.4.4发布时合并。注意`nevinee/qbittorrent:edge`标签当前没有arm64平台的，这个平台当前edge仓库的包有问题。 创建时增加GOTIFY_URL和GOTIFY_APP_TOKEN两个环境变量。如：
> 
> ```
> GOTIFY_URL=https://example.com:8080
> GOTIFY_APP_TOKEN=BRnbDJdtpf1Uh9
> ```

建议连GOTIFY_PRIORITY这个变量也加进去，解决通知优先级问题

**Comment by devome** [comment]
> 建议连GOTIFY_PRIORITY这个变量也加进去，解决通知优先级问题

已加，默认5，镜像已更新。
