### ISSUE TITLE
安装最新edge版，访问webui出现Unauthorized

### ISSUE THREAD

**Issue by spysir** [devome/dockerfiles#43]
把 WebUI\HostHeaderValidation=false 添加到配置文件也不起作用

**Comment by devome** [comment]
你先另开一个不使用旧配置全新配置的新容器试试看看。

**Comment by spysir** [comment]
> 你先另开一个不使用旧配置全新配置的新容器试试看看。

试过了还是出现Unauthorized，这是我的docker-compose.yml文件

![Snipaste_2022-07-29_13-31-42](https://user-images.githubusercontent.com/59646715/181689290-e2415f81-ba1b-4ea9-b667-cea0a09e8543.jpg)

**Comment by devome** [comment]
清空浏览器缓存后重启下浏览器呢？

**Comment by devome** [comment]
8080要改一起改，冒号两边要一致。不能容器内外不一致。

**Comment by spysir** [comment]
> 8080要改一起改，冒号两边要一致。不能容器内外不一致。

把 - 30599:8080 改成 - 8080:8080 终于搞定了，感谢大佬
