### ISSUE TITLE
请问有可能增加对单个种子设置下载进度到指定几个进度的时候发送推送提醒吗？

### ISSUE THREAD

**Issue by kevinyang225** [devome/dockerfiles#47]
比如对单个种子可以在右键设置 当下载进度到50%，80%，95%的时候 各发送一次推送提醒
下载进度可以根据total_downloaded/total_size计算获得

**Comment by devome** [comment]
需要借助其他手段实现，比如另跑一条程序，每隔10s检查下载中的种子及其进度，然后根据设定的百分比进行通知。

**Comment by kevinyang225** [comment]
感谢大佬回复 感觉1分钟一次应该足够了  也不用那么精确 10s太频繁了。。。
自己额外写个python脚本定时执行 比如用qbittorrentapi 遍历一遍所有的种子信息 对需要监控的种子进行推送 确实很容易能实现这功能 
可以搞几个配置项 比如对指定tag的种子进行进度推送 或者 对指定下载目录的种子进行进度推送
再配置下哪几个进度百分比需要进行推送 就差不多了
就是不知道大佬有没有可能把这功能集成到docker里 这样对有这需求但不会写代码的朋友 确实挺有帮助的

**Comment by devome** [comment]
这个需求我觉得不是很普遍，你可能需要自己实现。

**Comment by kevinyang225** [comment]
好的 感谢大佬回复
