### ISSUE TITLE
大神，能不能提2个建议啊~

### ISSUE THREAD

**Issue by cng10001** [devome/dockerfiles#52]
创建任务不如桌面版好用，提2个建议不知doker内可以实现吗~下载路径可以可视化选文件夹吗？如果喜欢放不同文件夹的话，每次都要手动填不方便哦；
还有个就是创建任务后正式开始前，还能调出创建子文件夹/不创建子文件夹嘛

**Comment by devome** [comment]
这个需求你只能像qBittorrent官方提issue哦。
