### ISSUE TITLE
qb建议：添加「自动按tracker添加『标签』」的功能

### ISSUE THREAD

**Issue by LoneFireBlossom** [devome/dockerfiles#56]
现在是可以实现自动按tracker进行分类，我感觉这样有一些不便之处，最核心的就是，这样的话没法使用qb的「自动torrent管理」（即将资源下载路径自动设定为种子分类对应的目录），我是把种子分类成电影、电视剧、动画、特摄、……的，每个分类放到自己的文件夹里。开启了自动torrent管理，又开启了自动按tracker分类的话，那多个站都有的资源是不是就会在各个站点的目录下到处移动，只有一个站能做种……
今天开始学习使用docker版本的qb，迁移种子的过程中看到分类慢慢地自己变化真是吓死我了😭😂😂😂，怕被站点认为是在做假种，吓得我赶紧停止了镜像，把被移动目录的种子再手动挪回去。重新装一个把这个功能关掉。

另外，有的站有多个tracker吧，例如IPT，如果按照tracker分类是不是就不好分了。（我发现上面的情况后立刻就停了，这条没敢再测试下去）

如果大佬打算实现这个功能的话，希望能支持一下4.3.9版本，由于4.4.0升级了那个libtorrent v2我看到好些抱怨，还有 https://github.com/devome/dockerfiles/issues/11 这个原因，我感觉要在4.3.9停留很久很久了

**Comment by devome** [comment]
已更新，详见 hub 简介 更新日志 和 环境变量清单。
