### ISSUE TITLE
qb-iyuu 内存占用高

### ISSUE THREAD

**Issue by lyj0309** [devome/dockerfiles#57]
![image](https://user-images.githubusercontent.com/50474995/203332194-1dbfdb3c-d70f-4394-b449-72e030d65d4c.png)

docker 版qb，不知道为啥内存一直慢慢涨，快到8g就停了，总内存就16g占一半

**Comment by lyj0309** [comment]
感觉是内存泄漏了

**Comment by devome** [comment]
请见问题18：https://github.com/devome/dockerfiles/blob/master/qbittorrent/qa.md

**Comment by lyj0309** [comment]
> 请见问题18：[https://github.com/devome/dockerfiles/blob/master/qbittorrent/qa.md](https://gh.fakev.cn/devome/dockerfiles/blob/master/qbittorrent/qa.md)

了解了，感谢
