### ISSUE TITLE
简体中文无法载入

### ISSUE THREAD

**Issue by Aziatixic** [devome/dockerfiles#59]
日志如下：
(W) 2022-11-29T12:21:29 - 無法載入所選語言（zh）的Web UI遠端控制翻譯。
(N) 2022-11-29T12:21:29 - Web UI遠端控制：正在監聽IP：*，埠：8080

**Comment by devome** [comment]
等官方修复：[18090](https://github.com/qbittorrent/qBittorrent/issues/18090)

**Comment by devome** [comment]
应用了一个补丁，可以正常使用简体中文了，参照docker hub上的更新日志说明进行处理。

**Comment by Aziatixic** [comment]
感谢！已成功切换中文。
