### ISSUE TITLE
请求选择性推送通知的功能（种子路经过滤）

### ISSUE THREAD

**Issue by leverule** [devome/dockerfiles#61]
有部分路径下种子下载删除频繁，不需要关注，请问可以忽略这些种子的通知吗，比如让通知功能可以按路径筛选

**Comment by devome** [comment]
这需求也太小众了吧。。你可以考虑自己实现一下看看，比如另写一个脚本`my-dl-finish.sh`：

```
#!/bin/bash

if [[ $2 = XXXX || $2 == XXXXX ]]; then
    dl-finish "$1"
fi
```
放到容器下`/data/diy/my-dl-finish.sh`，赋予可执行权限，然后在qBittorrent中设置“torrent 完成时运行外部程序”为`/data/diy/my-dl-finish.sh "%I" "%D"`。

**Comment by leverule** [comment]
谢谢大佬，我写的语法是出问题了吗，没成功...已排除网络问题，权限貌似也没问题？
![image](https://user-images.githubusercontent.com/57491211/205477314-55215419-bd2d-40b4-ab8c-32ccd9b2c883.png)
![image](https://user-images.githubusercontent.com/57491211/205477337-742ec4f2-ce5c-487c-8400-b61af73abdec.png)
![image](https://user-images.githubusercontent.com/57491211/205477356-7528dc96-2593-4394-a9d9-22120db2700b.png)

**Comment by leverule** [comment]
我是小白233，请问有没有可能是外部脚本里不能直接调用dl-finish呢，或者得填dl-finish具体路径？

**Comment by devome** [comment]
换行。这是/Meta/Others会通知。

**Comment by leverule** [comment]
是的，一直失败...想先填个简单路径做实验
换行也不行，直接复制格式再修改的，哎不知道哪里出了问题
换回原来的默认通知设置dl-finish，是没问题的
<img width="635" alt="Snipaste_2022-12-04_21-34-16" src="https://user-images.githubusercontent.com/57491211/205494051-a0307846-fe85-4e0a-970a-9ec98325766c.png">
<img width="447" alt="Snipaste_2022-12-04_21-37-50" src="https://user-images.githubusercontent.com/57491211/205494060-2a3b3191-78db-4f82-b01b-006c2925625f.png">
<img width="373" alt="Snipaste_2022-12-04_21-38-10" src="https://user-images.githubusercontent.com/57491211/205494066-a5be5d6f-29c9-41a1-80fd-c27e20b7c5df.png">
<img width="1067" alt="Snipaste_2022-12-04_21-39-21" src="https://user-images.githubusercontent.com/57491211/205494080-ccc42bf0-a124-47dc-b621-5e7d2340d70f.png">

**Comment by devome** [comment]
你可能是windows害的，windows的换行符是\r\n，而linux只认\的换行符，你用notepad++转换下格式吧。

**Comment by leverule** [comment]
哇 是的！！成功了！！学到啦，感谢大佬耐心指点！！
![image](https://user-images.githubusercontent.com/57491211/205500138-b013b862-e22c-4c93-8700-99696f2a0718.png)
