### ISSUE TITLE
有多个tracker的种子的tracker标签，有的打了所有tracker对应的标签，有的没有

### ISSUE THREAD

**Issue by LoneFireBlossom** [devome/dockerfiles#63]
例如IPT有三个tracker：
<img width="210" alt="image" src="https://user-images.githubusercontent.com/50087596/209429993-fbef2aed-3af5-4a46-9764-65550acdd3c7.png">

有的种子打了对应的三个标签，有的没有，用`docker exec qBittorrent auto-cat -A`运行了也还是这样：
<img width="339" alt="image" src="https://user-images.githubusercontent.com/50087596/209430003-bd8e563f-07ea-4c04-87f9-b69cf2587d04.png">
不知道是为什么？

qBittorrent 4.3.9，设置的是用标签标注tracker

**Comment by devome** [comment]
有多个tracker的只会打上其中一个的标签，具体是哪一个取决于种子中的tracker顺序。

**Comment by LoneFireBlossom** [comment]
但是有的种子是三个标签都打了呀，如上面图里所示

**Comment by LoneFireBlossom** [comment]
哦哦，明白了
