### ISSUE TITLE
北洋园的种子全是TrackerError

### ISSUE THREAD

**Issue by LoneFireBlossom** [devome/dockerfiles#65]
qBittorrent 4.3.9

如下图所示，我发现tjupt的种子全都会被打上trackererror的标签。我想这是因为北洋园的两个tracker中的第二个一定是无法连接的状态（只有天津大学校内的人第二个tracker才能连上），而这被设置这个标签的脚本认为是有问题的。
另外下图中朋友的种子似乎也有这样的问题，因为我朋友的种子不多所以不太确定。

如果大佬修改脚本的话，我想是不是可以这样，如果一个种子有多个tracker，那么只要其中有一个tracker是正常工作的就不打标签，所有tracker都不正常工作才打trackererror标签？

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/50087596/209468442-8d4967fb-676b-44a3-a7b9-6010bcc72ba1.png">

**Comment by devome** [comment]
仓库中的代码已经调整逻辑了，只要有一个tracker正常就不会再标记。不过还没有更新到镜像中。edge版本倒是更新了。

**Comment by LoneFireBlossom** [comment]
那我是等稳定版就可以了是么，等更新日志更新

**Comment by devome** [comment]
> 那我是等稳定版就可以了是么，等更新日志更新

更新4.5.1时同时更新4.3.9。
