### ISSUE TITLE
作者你好，本版qb内置了的iyuu，会伴随着功能缺失吗，我看不到图片上写的torrent文件夹

### ISSUE THREAD

**Issue by cng10001** [devome/dockerfiles#67]
![c2b5ff95a98dd98ec6a8ed1f5445f42](https://user-images.githubusercontent.com/115156545/210937574-88b1ddde-f091-46cf-b3eb-aa75084fb730.jpg)
如果要另外映射装载路径的话，应该如何设置呢

**Comment by devome** [comment]
iyuuplus程序在容器内的`/iyuu`目录，官方在`/IYUU`目录，仅把大写改成了小写，其他全部和官方一致，官方如何操作就如何操作。`torrent`目录在`/iyuu/runtime`下，对官方的来说，就是`/IYUU/runtime`，至于能不能映射，以官方教程为准。

**Comment by cng10001** [comment]
关于runtime的说明和映射方法，倒是网上都找不到- 。
你dockerhub上的目录说明iyuuplus文件夹默认应该是/iyuu_db，再根据你说的瞎倒腾了了下，最终如图设置成功 ![iyuu](https://user-images.githubusercontent.com/115156545/211150755-f6266563-ad4e-416c-baaf-ba78affdfcd1.jpg)
不知道之前是不是文件夹目录创建错成了/iyuu_db/runtime还是装载路径写成大写/IYUU/rutime的问题了
