### ISSUE TITLE
QB的自动分类会覆盖某些程序的分类

### ISSUE THREAD

**Issue by LoSiTeE** [devome/dockerfiles#92]
用AutoBangumi追番，它本身会给下载进行分类，但是我发现当完成下载的时候QB会自动覆盖其分类。同样会自动分类的NAStool，它的下载项目分类就不会被QB的自动分类所覆盖。

请问我是哪里设置的不对，还是AutoBangumi程序的问题。

如果是设置问题，环境变量应如何设置才能达到“AutoBangumi的自动分类不会被QB的自动分类所覆盖”这个要求？

感谢。

**Comment by devome** [comment]
一般是后设置的覆盖先设置的。

既然要使用其他程序来分类，那么就建议关闭我这边的自动分类：把`ENABLE_AUTO_CATEGORY`设置为`false`。

**Comment by LoSiTeE** [comment]
震惊，秒回啊大佬~
我还是有一点疑问：
<html>
<body>


27 | CRON_AUTO_CATEGORY | 32 */2 * * * | 自动分类的cron，在设定的cron运行auto-cat -a命令，将所有未分类种子按tracker分类（当CATEGORY_OR_TAG=category时），或将所有种子按tracker打标签（当CATEGORY_OR_TAG=tag时）。对于种子很多的大户人家，建议把cron频率修改低一些，一天一次即可。此cron可以由ENABLE_AUTO_CATEGORY关闭，关闭后不生效。虽然本变量是全版本有效，但控制采用“分类”还是“标签”的变量CATEGORY_OR_TAG仅4.3.9和4.5.0+有效。
-- | -- | -- | --



</body>
</html>

这个环境变量里说的是运行auto-cat -a命令会对**“未分类”**的种子按tracker进行分类，我的这个需求确实无法兼得吗？

因为nastool的自动分类功能就不会被QB的自动分类覆盖掉，是否可以再想想办法？

**Comment by devome** [comment]
那就ENABLE_AUTO_CATEGORY仍然设置为true，同时按照#82 处理一下。

**Comment by LoSiTeE** [comment]
> 那就ENABLE_AUTO_CATEGORY仍然设置为true，同时按照#82 处理一下。

大佬，我尬住了。这个文件在哪儿啊？我黑群6.23，找了好久没找到

**Comment by devome** [comment]
容器内的/usr/local/bin/dl-finish
